### PR TITLE
update mermaid to version v8.14.0

### PR DESCRIPTION
**Pull request by mojerro**
Hello, I want to update mermaid to version v8.14, could you please have a check when you are free~

### CODE REVIEW

**Comment by DanielFlaum** [comment]
Hey @mojerro, thanks so much for prepping a PR. I'll test it in the next couple of days and merge if I see no problems. Thanks!

**Comment by mojerro** [comment]
also thanks for spending time doing the test 😄

**Review by DanielFlaum — APPROVED** [review]

**Comment by DanielFlaum** [comment]
Basic testing was successful. I've merged and pushed out a new release. The Grav project's infrastructure should automatically pick it up and make it available to Grav users shortly.

Thanks so much @mojerro!

**Comment by mojerro** [comment]
😆

**Pull request closed without merging**
